<a href="https://colab.research.google.com/github/harishri10/AIML_assignments_and_projects/blob/main/2505047_task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print(np.__version__)

2.0.2


**LISTS**

In [ ]:
import numpy as np
list1=[1,2,3,4,5]
list2=[10,9,8,7,6]
print("list 1: ",list1)
print("list 2: ",list2)

list 1:  [1, 2, 3, 4, 5]
list 2:  [10, 9, 8, 7, 6]


**BASIC OPERATIONS ON LISTS**

In [ ]:
import numpy as np
list1=[1,2,3,4,5]
list2=[10,9,8,7,6]
print('sum= ',list1+list2)

sum=  [1, 2, 3, 4, 5, 10, 9, 8, 7, 6]


In [ ]:
import numpy as np
list1=[1,2,3,4,5]
list2=[10,9,8,7,6]
print('difference= ',list2-list1)
print('product= ',list1*list2)
print('division= ',list2/list1)

TypeError: unsupported operand type(s) for -: 'list' and 'list'

You can't subtract one list from another like you would with numbers. Python lists don't understand what it means to subtract elements directly. You need to perform the subtraction element-wise, which means you need to subtract corresponding elements from each list.

Subtraction: To perform element-wise subtraction, we import numpy and use the np.subtract function, which takes two arrays (or lists that will be converted to arrays) as arguments. This will subtract corresponding elements and return a new array.

Multiplication and Division: Lists do not natively support these operations. However, list comprehension was applied for element-wise multiplication and division.

**CONVERTING LISTS INTO ARRAYS**

In [ ]:
import numpy as np
list1=[1,2,3,4,5]
list2=[5,4,3,2,1]
a1=np.array(list1)
a2=np.array(list2)
print("array1: ",a1)
print("array2: ",a2)

array1:  [1 2 3 4 5]
array2:  [5 4 3 2 1]


**CONVERTING LISTS INTO ARRAYS AND PERFORMING BASIC OPERATIONS**

In [ ]:
import numpy as np
list1=[1,2,3,4,5]
list2=[5,4,3,2,1]
a1=np.array(list1)
a2=np.array(list2)
print('sum= ',a1+a2)
print('difference= ',a2-a1)
print('product= ',a1*a2)
print('division= ',a2/a1)

sum=  [6 6 6 6 6]
difference=  [ 4  2  0 -2 -4]
product=  [5 8 9 8 5]
division=  [5.  2.  1.  0.5 0.2]


**BASIC FUNCTIONS ON ARRAYS**

In [ ]:
import numpy as np
arr = np.array( [[1,2,3],
                 [4,2,5]] )
print("aray is of type: ",type(arr))
print("no. of dimension: ",arr.ndim)
print("shape of the array: ",arr.shape)
print("size of the array: ",arr.size)
print("data type of array: ",arr.dtype)
print("the array is: ",arr)

In [ ]:
import numpy as np
a=np.arange(10,1,-2)
print(a)
newarr=a[np.array([3,1,2])]
print(newarr)

[10  8  6  4  2]
[4 8 6]


In [ ]:
import numpy as np
x=np.array([1,2,3,4,5,6,7,8,9])
arr1=x[np.array([1,3,-3])]
print('array1: ',arr1)
arr2=x[np.array([-6,0,1])]
print('array2: ',arr2)

array1:  [2 4 7]
array2:  [4 1 2]


In [ ]:
import numpy as np
a=np.arange(20)
print(a)
print(a[-8:17:1])
print(a[10: ])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[12 13 14 15 16]
[10 11 12 13 14 15 16 17 18 19]


In [ ]:

import numpy as np
array = np.arange(10, 51)
even_numbers = array[array % 2 == 0]
print("Original Array:",array)
print("\nEven Numbers:",even_numbers)

Original Array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]

Even Numbers: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


**RESHAPING ARRAY**

In [ ]:
import numpy as np
array_1d = np.arange(1, 21)
print("One-dimensional Array:")
print(array_1d)
array_2d = array_1d.reshape(4,5)
print("\nReshaped 4X5 Matrix:")
print(array_2d)

One-dimensional Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Reshaped 4X5 Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
import numpy as np
a=np.array([[1,2,4],[5,8,7]],dtype='float')
print("Array created using passed list:\n",a)
b=np.array((1,3,2))
print("Array created using passed tuple:\n",b)

Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]
Array created using passed tuple:
 [1 3 2]


**ZEROES**

In [ ]:
import numpy as np
arr_1d = np.zeros(5)
print('1D array with zeros:', arr_1d)
arr_2d = np.zeros((2, 3))
#2*3 array
print('2D array with zeros:\n', arr_2d)
arr_3d = np.zeros((2, 3, 4 ))
#2*3*4 array
print('3D array with zeros:\n', arr_3d)

1D array with zeros: [0. 0. 0. 0. 0.]
2D array with zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
3D array with zeros:
 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


**DATA TYPES**

In [ ]:
import numpy as np
a=9067587
print(type(a))
b=str(a)
print(type(b))
c='hi'
print(type(c))
d=78.87
print(type(d))
e=0
print(type(e))
f=True
print(type(f))
g=None
print(type(g))

<class 'int'>
<class 'str'>
<class 'str'>
<class 'float'>
<class 'int'>
<class 'bool'>
<class 'NoneType'>


**CREATING A 11D ARRAY**

In [ ]:
import numpy as np
arr=np.array([1,2,3,4],ndmin=11)
print(arr)
print('number of dimensions: ',arr.ndim)

[[[[[[[[[[[1 2 3 4]]]]]]]]]]]
number of dimensions:  11


**TO LEARN ABOUT OUTER PRODUCT**

Think of the Outer Product as "Multiplying a Column by a Row"

Suppose you have two 1D vectors:

-> u = [1, 2, 3] → think of this as a column vector (vertical)

-> v = [4, 5] → think of this as a row vector (horizontal)

The outer product creates a matrix where:

-> Every element of u is multiplied by every element of v

-> The result is a table (2D array) of all combinations of u[i] * v[j]


Let's analyse using a python code

In [ ]:
import numpy as np

u = np.array([1, 2, 3])
v = np.array([4, 5])

outer = np.outer(u, v)
print(outer)


[[ 4  5]
 [ 8 10]
 [12 15]]


Here, each row of the resulting matrix is the vector v multiplied by the corresponding element in u.

This operation is distinct from the dot product, which produces a scalar. The outer product yields a matrix, capturing all pairwise multiplications between elements of the two vectors.


Why It’s Useful:

-> Creates rank-1 matrices (building blocks of larger matrices)

->
Forms the basis for tensor products, machine learning weights, quantum states, etc.

**TO CREATE A METHOD TO PERFORM: ADDITION, SUBTRACTION, MULTIPLICATION, DOT PRODUCT, MATRIX MULTIPLICATION, DETERMINANT, INVERSE OF TWO MATRICES**

In [ ]:
import numpy as np

# Predefined matrices
A = np.array([[2, 4], [1, 3]])
B = np.array([[5, 2], [0, 1]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

# Addition
try:
    print("\nAddition:\n", A + B)
except:
    print("\nAddition not possible.")

# Subtraction
try:
    print("\nSubtraction:\n", A - B)
except:
    print("\nSubtraction not possible.")

# Element-wise Multiplication
try:
    print("\nElement-wise Multiplication:\n", A * B)
except:
    print("\nElement-wise multiplication not possible.")

# Dot Product
try:
    print("\nDot Product:\n", np.dot(A, B))
except:
    print("\nDot product not possible.")

# Matrix Multiplication
try:
    print("\nMatrix Multiplication (A @ B):\n", A @ B)
except:
    print("\nMatrix multiplication not possible.")

# Determinant of A
if A.shape[0] == A.shape[1]:
    try:
        print("\nDeterminant of A:", round(np.linalg.det(A), 2))
    except:
        print("\nDeterminant could not be calculated.")
else:
    print("\nMatrix A is not square. Cannot compute determinant.")

# Inverse of A
if A.shape[0] == A.shape[1]:
    try:
        print("\nInverse of A:\n", np.linalg.inv(A))
    except:
        print("\nMatrix A is singular (non-invertible).")
else:
    print("\nMatrix A is not square. Cannot compute inverse.")

Matrix A:
 [[2 4]
 [1 3]]
Matrix B:
 [[5 2]
 [0 1]]

Addition:
 [[7 6]
 [1 4]]

Subtraction:
 [[-3  2]
 [ 1  2]]

Element-wise Multiplication:
 [[10  8]
 [ 0  3]]

Dot Product:
 [[10  8]
 [ 5  5]]

Matrix Multiplication (A @ B):
 [[10  8]
 [ 5  5]]

Determinant of A: 2.0

Inverse of A:
 [[ 1.5 -2. ]
 [-0.5  1. ]]
