<a href="https://colab.research.google.com/github/harishri10/AIML_assignments_and_projects/blob/main/2505047_task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TO LEARN ABOUT OUTER PRODUCT**

Think of the Outer Product as "Multiplying a Column by a Row"

Suppose you have two 1D vectors:

-> u = [1, 2, 3] → think of this as a column vector (vertical)

-> v = [4, 5] → think of this as a row vector (horizontal)

The outer product creates a matrix where:

-> Every element of u is multiplied by every element of v

-> The result is a table (2D array) of all combinations of u[i] * v[j]


Let's analyse using a python code

In [1]:
import numpy as np

u = np.array([1, 2, 3])
v = np.array([4, 5])

outer = np.outer(u, v)
print(outer)


[[ 4  5]
 [ 8 10]
 [12 15]]


Here, each row of the resulting matrix is the vector v multiplied by the corresponding element in u.

This operation is distinct from the dot product, which produces a scalar. The outer product yields a matrix, capturing all pairwise multiplications between elements of the two vectors.


Why It’s Useful:

-> Creates rank-1 matrices (building blocks of larger matrices)

->
Forms the basis for tensor products, machine learning weights, quantum states, etc.



**TO CREATE A METHOD TO PERFORM: ADDITION, SUBTRACTION, MULTIPLICATION, DOT PRODUCT, MATRIX MULTIPLICATION, DETERMINANT, INVERSE OF TWO MATRICES**

In [2]:
import numpy as np

# Predefined matrices
A = np.array([[2, 4], [1, 3]])
B = np.array([[5, 2], [0, 1]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

# Addition
try:
    print("\nAddition:\n", A + B)
except:
    print("\nAddition not possible.")

# Subtraction
try:
    print("\nSubtraction:\n", A - B)
except:
    print("\nSubtraction not possible.")

# Element-wise Multiplication
try:
    print("\nElement-wise Multiplication:\n", A * B)
except:
    print("\nElement-wise multiplication not possible.")

# Dot Product
try:
    print("\nDot Product:\n", np.dot(A, B))
except:
    print("\nDot product not possible.")

# Matrix Multiplication
try:
    print("\nMatrix Multiplication (A @ B):\n", A @ B)
except:
    print("\nMatrix multiplication not possible.")

# Determinant of A
if A.shape[0] == A.shape[1]:
    try:
        print("\nDeterminant of A:", round(np.linalg.det(A), 2))
    except:
        print("\nDeterminant could not be calculated.")
else:
    print("\nMatrix A is not square. Cannot compute determinant.")

# Inverse of A
if A.shape[0] == A.shape[1]:
    try:
        print("\nInverse of A:\n", np.linalg.inv(A))
    except:
        print("\nMatrix A is singular (non-invertible).")
else:
    print("\nMatrix A is not square. Cannot compute inverse.")


Matrix A:
 [[2 4]
 [1 3]]
Matrix B:
 [[5 2]
 [0 1]]

Addition:
 [[7 6]
 [1 4]]

Subtraction:
 [[-3  2]
 [ 1  2]]

Element-wise Multiplication:
 [[10  8]
 [ 0  3]]

Dot Product:
 [[10  8]
 [ 5  5]]

Matrix Multiplication (A @ B):
 [[10  8]
 [ 5  5]]

Determinant of A: 2.0

Inverse of A:
 [[ 1.5 -2. ]
 [-0.5  1. ]]
